// Generated by Website Factory. Update via the factory pipeline, not by hand.

export type WeekdayHours = {
  day: string;
  time: string;
  closed: boolean;
};

export type RestaurantConfig = {
  name: string;
  shortName: string;
  tagline: string;
  logoGlyph: string;
  cuisine: string;
  website?: string;
  priceRange?: string;
  coordinates?: {
    latitude: number;
    longitude: number;
  };
  nativeTagline: string;
  nativeTaglineTranslation: string;
  phone: string;
  phoneLink: string;
  landlinePhone?: string;
  landlinePhoneLink?: string;
  email: string;
  address: {
    street: string;
    cityLine: string;
    city: string;
  };
  mapsUrl: string;
  googleBusinessProfileUrl: string;
  socialMedia: {
    instagram: string;
    facebook: string;
    tiktok: string;
    hidden: {
      instagram: boolean;
      facebook: boolean;
      tiktok: boolean;
    };
    titleHidden: boolean;
  };
  closedDays: number[];
  closedDaysLabel: string;
  hours: WeekdayHours[];
  reservationTimeSlots: {
    startHour: number;
    endHour: number;
    stepMinutes: number;
    latestMinutes: number;
  };
  seo: {
    title: string;
    description: string;
    keywords: string[];
    ogTitle: string;
    ogDescription: string;
    locale: string;
  };
  legal: {
    ownerName: string;
    vatId: string;
    responsiblePerson: string;
  };
};

export const restaurant: RestaurantConfig = {
  "name": "SB-Gartengestaltung",
  "shortName": "SB-Gartengestaltung",
  "tagline": "Garten- und Landschaftsbau",
  "logoGlyph": "S",
  "cuisine": "Garten- und Landschaftsbau",
  "nativeTagline": "",
  "nativeTaglineTranslation": "",
  "phone": "01575 3810244",
  "phoneLink": "tel:+4915753810244",
  "email": "",
  "address": {
    "street": "Triftweg 71",
    "cityLine": "67098 Bad Dürkheim",
    "city": "Bad Dürkheim"
  },
  "mapsUrl": "https://maps.google.com/?cid=5758776351847188165&g_mp=CiVnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLkdldFBsYWNlEAIYBCAA",
  "googleBusinessProfileUrl": "https://maps.google.com/?cid=5758776351847188165&g_mp=CiVnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLkdldFBsYWNlEAIYBCAA",
  "socialMedia": {
    "instagram": "https://instagram.com/sbgartengestaltung.baddurkheim",
    "facebook": "https://facebook.com/sbgartengestaltungbaddurkheim",
    "tiktok": "https://tiktok.com/@sbgartengestaltung.baddurkheim",
    "hidden": {
      "instagram": true,
      "facebook": true,
      "tiktok": true
    },
    "titleHidden": true
  },
  "closedDays": [
    6,
    0
  ],
  "closedDaysLabel": "Geschlossen: Samstag & Sonntag.",
  "hours": [
    {
      "day": "Montag, Dienstag, Mittwoch & Donnerstag",
      "time": "08:00–18:00 Uhr",
      "closed": false
    },
    {
      "day": "Freitag",
      "time": "08:00–17:00 Uhr",
      "closed": false
    },
    {
      "day": "Samstag & Sonntag",
      "time": "Geschlossen",
      "closed": true
    }
  ],
  "reservationTimeSlots": {
    "startHour": 17,
    "endHour": 21,
    "stepMinutes": 30,
    "latestMinutes": 30
  },
  "seo": {
    "title": "SB-Gartengestaltung | Garten- und Landschaftsbau in Bad Dürkheim",
    "description": "SB-Gartengestaltung in Bad Dürkheim. Gartengestaltung, Pflasterarbeiten, Terrassenbau und Gartenpflege. Projekt online anfragen, Antwort innerhalb von 24 Stunden.",
    "keywords": [
      "SB-Gartengestaltung",
      "Garten- und Landschaftsbau Bad Dürkheim",
      "Gartengestaltung Bad Dürkheim",
      "Pflasterarbeiten Bad Dürkheim",
      "Terrassenbau Bad Dürkheim"
    ],
    "ogTitle": "SB-Gartengestaltung",
    "ogDescription": "SB-Gartengestaltung in Bad Dürkheim. Gartengestaltung, Pflasterarbeiten, Terrassenbau und Gartenpflege. Projekt online anfragen, Antwort innerhalb von 24 Stunden.",
    "locale": "de_DE"
  },
  "legal": {
    "ownerName": "",
    "vatId": "",
    "responsiblePerson": ""
  }
};

export function isClosedDay(dateStr: string): boolean {
  if (!dateStr) return false;
  const day = new Date(dateStr).getDay();
  return restaurant.closedDays.includes(day);
}

export function generateTimeSlots(): string[] {
  const startHour: number = restaurant.reservationTimeSlots.startHour;
  const endHour: number = restaurant.reservationTimeSlots.endHour;
  const stepMinutes: number = restaurant.reservationTimeSlots.stepMinutes;
  const latestMinutes: number = restaurant.reservationTimeSlots.latestMinutes;
  const slots: string[] = [];
  for (let hour = startHour; hour <= endHour; hour++) {
    for (let minute = 0; minute < 60; minute += stepMinutes) {
      if (hour === endHour && minute > latestMinutes) break;
      const hh = hour.toString().padStart(2, "0");
      const mm = minute.toString().padStart(2, "0");
      slots.push(`${hh}:${mm}`);
    }
  }
  return slots;
}
