// Generated by Website Factory. Update via the factory pipeline, not by hand.

export type Review = {
  author: string;
  rating: number;
  text: string;
  time: string;
};

export type ReviewsData = {
  overallRating: number;
  totalRatings: number;
  reviews: Review[];
};

export const reviewsDataGeneratedFromFactory = true;

export const reviewsData: ReviewsData = {
  "overallRating": 5,
  "totalRatings": 1,
  "reviews": [
    {
      "author": "Uwe Schäfer",
      "rating": 5,
      "text": "Wir haben von der Firma einen Doppelstabmattenzaun errichten lassen und waren äußerst zufrieden. Beratung, Kommunikation, Termintreue sowie die Präzision und Sauberkeit in der Ausführung haben uns absolut überzeugt.\nWir würden dieser Firma jederzeit wieder einen Auftrag anvertrauen.",
      "time": "vor 5 Monaten"
    }
  ]
};
